version: '1'
services:
  web:
    build: .
    command: sh -c "uvicorn model_app:app --reload --host 0.0.0.0 --port 8090"
    env_file: 
      - .env.developement
    ports:
      - 8090:8090
    volumes:
      - .:/app


#docker compose build
#docker compose up

